---
title: "build_gam"
author: "Carrie Hashimoto"
date: "2024-07-26"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(comment = NA)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r, warning = FALSE, message = FALSE}
packages <- c('tidyverse','mgcv','gam','akima','readr','data.table','vroom',
              'foreach','doParallel','readr','caret')

# Identify missing (not installed) packages
new.packages <-  packages[!(packages %in% installed.packages()[,"Package"])]

# Install new (not installed) packages
if(length(new.packages)) install.packages(new.packages, repos='http://cran.rstudio.com/') else print('All required packages are installed.')

invisible(lapply(packages, library, character.only = TRUE))
```

```{r}
wd <- rprojroot::find_rstudio_root_file()
outDir <- file.path(wd, "Data", fsep="/")
suppressWarnings(dir.create(outDir)) 

num_cores <- detectCores() - 1
cl <- makeCluster(num_cores - 1)  # Use one less core than available
registerDoParallel(cl)
```

```{r}
df_final <- vroom::vroom("intermediate_results.csv")
df_final$rET <- df_final$aET / df_final$prefire_ET * 100

df_final$rET # make sure this is actually in percent

# remove rows with NAs - all in aspect - why?
df_clean <- na.omit(df_final)

model_df <- df_clean[c("aET","rET","lat","lon","dNDVI","dNBR","temp","precip",
                       "elev","aspect","slope","soil_moisture")]

# get a subset for visualization
set.seed(0)

k <- 1000
n <- nrow(df_clean)

folds <- sample(rep(1:k, length = n))

model_df_fold1 <- model_df[folds == 1, ]
```

```{r}
# make the GAM
# first use all predictors, no interaction terms

# Fit the model using bam
bam_aET <- mgcv::bam(rET ~ s(temp, bs = "cs", k = 50) + s(precip, bs = "cs", k = 50) +
                       s(elev, bs = "cs", k = 60) + s(aspect, bs = "cs", k = 50) + 
                       s(slope, bs = "cs", k = 50) + s(soil_moisture, bs = "cs", k = 50) +
                       s(dNDVI, bs = "cs", k = 40) + s(dNBR, bs = "cs", k = 40) +
                       s(lon, bs = "cs", k = 60) + s(lat, bs = "cs", k = 60),
                     data = df_clean, method = "fREML")

# check model diagnostics
par(mfrow = c(2, 2))
gam.check(bam_aET) 


```
```{r}
# try increasing the basis dimensions
# first use all predictors, no interaction terms

# Fit the model using bam
bam_aET <- mgcv::bam(rET ~ s(temp, bs = "cs", k = 50) + s(precip, bs = "cs", k = 50) +
                       s(elev, bs = "cs", k = 60) + s(aspect, bs = "cs", k = 50) + 
                       s(slope, bs = "cs", k = 50) + s(soil_moisture, bs = "cs", k = 50) +
                       s(dNDVI, bs = "cs", k = 40) + s(dNBR, bs = "cs", k = 40) +
                       s(lon, bs = "cs", k = 60) + s(lat, bs = "cs", k = 60),
                     data = df_clean, method = "fREML")

# check model diagnostics
par(mfrow = c(2, 2))
gam.check(bam_aET) 


```



```{r}
# Ok, so the model isn't varied enough

# first try adding interaction terms

# based on the linear model, some interactions of interest are these
bam_aET_16_te <- mgcv::bam(rET ~ te(lat, bs = "cr") + te(lon, bs = "c") +
                       te(dNBR, bs = "cs") + te(temp, bs = "cs") +
                       te(aspect, bs = "cs") + te(soil_moisture, bs = "cs") +
                       ti(dNBR, temp, bs = "cs") + ti(dNBR, elev, bs = "cs") +
                       ti(temp, precip, bs = "cs") + ti(precip, elev, bs = "cs") +
                       ti(temp, aspect, bs = "cs") + ti(temp, slope, bs = "cs") +
                       ti(precip, elev, bs = "cs") + ti(precip, slope, bs = "cs") +
                       ti(precip, soil_moisture, bs = "cs") +
                       ti(elev, aspect, bs = "cs"),
                     data = model_df, method = "fREML")

summary(bam_aET_16_te)
gam.check(bam_aET_16_te)
```
```{r}
model_df
```


```{r}
# Try applying a log transformation
model_df$log_rET <- log(model_df$rET + abs(min(model_df$rET)) + 1)

# Fit the model
bam_aET_16_log <- mgcv::bam(log_rET ~ s(lat, bs = "cs") + s(lon, bs = "cs") +
                           s(dNBR, bs = "cs") + s(temp, bs = "cs") +
                           s(aspect, bs = "cs") + s(soil_moisture, bs = "cs") +
                           ti(dNBR, temp, bs = "cs") + ti(dNBR, elev, bs = "cs") +
                           ti(temp, precip, bs = "cs") + ti(precip, elev, bs = "cs") +
                           ti(temp, aspect, bs = "cs") + ti(temp, slope, bs = "cs") +
                           ti(precip, elev, bs = "cs") + ti(precip, slope, bs = "cs") +
                           ti(precip, soil_moisture, bs = "cs") +
                           ti(elev, aspect, bs = "cs"),
                         data = model_df, method = "fREML")

summary(bam_aET_16_log)

gam.check(bam_aET_16_log)
```



```{r}
bam_rET_16 <- mgcv::bam(rET ~ s(lat, bs = "tp", k = 100) + s(lon, bs = "tp", k = 100) +
                       s(dNBR, bs = "tp", k = 100) + s(temp, bs = "tp", k = 100) +
                       s(aspect, bs = "tp", k = 100) + s(soil_moisture, bs = "tp", k = 100) +
                       ti(dNBR, temp, bs = "tp") + ti(dNBR, elev, bs = "tp") +
                       ti(temp, precip, bs = "tp") + ti(precip, elev, bs = "tp") +
                       ti(temp, aspect, bs = "tp") + ti(temp, slope, bs = "tp") +
                       ti(precip, elev, bs = "tp") + ti(precip, slope, bs = "tp") +
                       ti(precip, soil_moisture, bs = "tp") +
                       ti(elev, aspect, bs = "tp"),
                     data = model_df, method = "fREML")
 
save(bam_rET_16, file = "bam_rET_16.RData")

gam.check(bam_rET_16)

```

```{r}
# take a look at fitted values... fear

fv_fold1 <- fitted_values(gam_rET_full_no_interaction, data = model_df_fold1)

names(fv)

ggplot(data=fv) +
  geom_point(aes(x=elev,y=.fitted,color="GAM fitted values")) +
  geom_point(aes(x=elev,y=rET,color="Response")) +
  scale_color_viridis_d(option = "D") +
  labs(title="rET vs elevation: response and GAM fitted values",
       x="Elevation(m)", y="rET (%)")

```


```{r}
stopCluster(cl)
registerDoSEQ()
```

