---
title: "create_filtered_rasters"
author: "Carrie Hashimoto"
date: "2024-07-25"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(comment = NA)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```


```{r}
# load necessary packages
library(terra)
library(tidyterra)
library(ggplot2)
library(rprojroot)
library(gridExtra)

# define output directory
wd <- rprojroot::find_rstudio_root_file()
outDir <- file.path(wd, "Data/", fsep="/")
suppressWarnings(dir.create(outDir)) 

# load prefire ET raster
prefire_et <- terra::rast(paste0(outDir,"/openET_data/tiffs/prefire_mean_ET.tif"))
ggplot() +
  geom_spatraster(data=prefire_et)

# get all the dates for which you have scenes
all_files <- list.files(paste0(outDir, "/HLS_data/red/"))
scene_files <- all_files[grepl("merged", all_files)] # don't want individual pieces

# extract the scene dates
scene_dates <- as.Date(sapply(scene_files, FUN=function(x) {
  substr(strsplit(x, "_")[[1]][2], start=2, stop=11)
}))

# extract whether it's from Landsat or Sentinel
scene_labels <- sapply(scene_files, FUN=function(x) {
  substr(strsplit(x, "_")[[1]][2], start=1, stop=1)
})

# Load the NIR, RED, and SWIR2 rasters
bands <- c("red", "nir", "swir2", "fmask")
stacks <- list()

# Collect all the rasters in stacks
for (i in 1:length(bands)) {
  band_stack <- list()
  for (j in 1:length(scene_dates)) {
    raster_path <- paste0(outDir, "/HLS_data/", bands[i], "/", bands[i], "_", scene_labels[j], scene_dates[j], "_merged.tiff")
    band_stack[[j]] <- terra::resample(terra::rast(raster_path), prefire_et)
  }
  stacks[[bands[i]]] <- band_stack
}


# define functions to calculate NDVI and NBR
calculate_ndvi <- function(nir, red){
  (nir - red) / (nir + red)
}

calculate_nbr <- function(nir, swir2){
  (nir - swir2) / (nir + swir2)
}

# initialize NDVI and NBR stacks
ndvi_stack <- list()
nbr_stack <- list()

# calculate NDVI and NBR for each scene
for (t in 1:length(scene_dates)) {
  if (!is.null(stacks$nir[[t]]) & !is.null(stacks$red[[t]]) & !is.null(stacks$swir2[[t]])) {
    ndvi_stack[[t]] <- calculate_ndvi(stacks$nir[[t]], stacks$red[[t]])
    nbr_stack[[t]] <- calculate_nbr(stacks$nir[[t]], stacks$swir2[[t]])
    
    # save scene dates
    names(ndvi_stack[[t]]) <- names(nbr_stack[[t]]) <- scene_dates[t]
  } else {
    message(paste("Missing data for date:", scene_dates[t]))
  }
}

# check the results - currently have a lot of bad values
ggplot() +
  geom_spatraster(data=ndvi_stack[[1]]) +
  ggtitle("NDVI for first scene")

ggplot() +
  geom_spatraster(data=nbr_stack[[5]]) +
  ggtitle("NBR for fifth scene")

## remove suspect values

# initialize cleaned stacks
ndvi_stack_cleaned <- list()
nbr_stack_cleaned <- list()

for (i in 1:length(ndvi_stack)) {
    ndvi_layer <- ndvi_stack[[i]]
    nbr_layer <- nbr_stack[[i]]
  
    # remove any values outside of (-1, 1)
    ndvi_layer[ndvi_layer < -1 | ndvi_layer > 1] <- NA
    nbr_layer[nbr_layer < -1 | nbr_layer > 1] <- NA
    
    # remove any remaining non-finite values... they should be gone already
    ndvi_layer[!is.finite(ndvi_layer)] <- NA
    nbr_layer[!is.finite(nbr_layer)] <- NA
    
    # save the cleaned scene
    ndvi_stack_cleaned[[i]] <- ndvi_layer
    nbr_stack_cleaned[[i]] <- nbr_layer
}

# look at the cleaned results
ggplot() +
  geom_spatraster(data=ndvi_stack_cleaned[[1]]) +
  ggtitle("Cleaned NDVI for first scene")

ggplot() +
  geom_spatraster(data=nbr_stack_cleaned[[5]]) +
  ggtitle("Cleaned NBR for fifth scene")

# define the function to apply the quality filter
apply_quality_filter <- function(ndvi_raster, quality_raster) {
  
  # create a mask from the quality raster
  masking_layer <- quality_raster
  
  # define the acceptable quality criteria (bits 7-6 should be 01 or 00)
  # it's an 8-bit value, so it must be under 128 in decimal
  # if you want bit 7 to be 0
  masking_layer[!(masking_layer / 128 < 1)] <- NA
  
  # mask the NDVI raster with the quality mask
  masked_ndvi <- mask(ndvi_raster, masking_layer, maskvalue=NA)
  
  return(masked_ndvi)
}

# apply the quality filter to each NDVI raster
filtered_ndvi_stack <- mapply(apply_quality_filter, ndvi_stack_cleaned, stacks[[4]], SIMPLIFY=FALSE)

# check the results
ggplot() +
  geom_spatraster(data=filtered_ndvi_stack[[9]]) +
  ggtitle("Filtered NDVI example")

# average over the time periods (only using JJA for 2020 and 2021, so just split by year)
prefire_indices <- as.vector(which(format(scene_dates, "%Y") == "2020"))
postfire_indices <- as.vector(which(format(scene_dates, "%Y") == "2021"))

# calculate the mean NDVI and NBR for the prefire period

# split the stack
prefire_ndvi_stack <- terra::rast(ndvi_stack_cleaned[prefire_indices])

# apply mean to get average summer NDVI
prefire_ndvi <- terra::app(prefire_ndvi_stack, fun=mean, na.rm=TRUE)

# same with NBR
prefire_nbr_stack <- terra::rast(nbr_stack_cleaned[prefire_indices])
prefire_nbr <- terra::app(prefire_nbr_stack, fun=mean, na.rm=TRUE)

# calculate the mean NDVI and NBR for the postfire period too
postfire_ndvi_stack <- terra::rast(ndvi_stack_cleaned[postfire_indices])
postfire_ndvi <- terra::app(postfire_ndvi_stack, fun=mean, na.rm=TRUE)

postfire_nbr_stack <- terra::rast(nbr_stack_cleaned[postfire_indices])
postfire_nbr <- terra::app(postfire_nbr_stack, fun=mean, na.rm=TRUE)

# take a look at the means
prefire_ndvi_plot <- ggplot() +
  geom_spatraster(data=prefire_ndvi) +
  ggtitle("Prefire NDVI mean")

postfire_ndvi_plot <- ggplot() +
  geom_spatraster(data=postfire_ndvi) +
  geom_spatvector(data=creekfire_geojson, fill=NA, color="red") +
  ggtitle("Postfire NDVI mean")

grid.arrange(prefire_ndvi_plot, postfire_ndvi_plot, ncol=2)

prefire_nbr_plot <- ggplot() +
  geom_spatraster(data=prefire_nbr) +
  ggtitle("Prefire NBR mean") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  scale_color_viridis_c() +
  scale_fill_viridis_c()

postfire_nbr_plot <- ggplot() +
  geom_spatraster(data=postfire_nbr) +
  geom_spatvector(data=creekfire_geojson, fill=NA) +
  ggtitle("Postfire NBR mean") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  scale_color_viridis_c() +
  scale_fill_viridis_c()


together <- grid.arrange(prefire_nbr_plot, postfire_nbr_plot, ncol=2)
together

# Save the processed rasters
terra::writeRaster(prefire_ndvi, paste0(outDir, "/prefire_mean_ndvi.tif"), overwrite=TRUE)
terra::writeRaster(prefire_nbr, paste0(outDir, "/prefire_mean_nbr.tif"), overwrite=TRUE)
terra::writeRaster(postfire_ndvi, paste0(outDir, "/postfire_mean_ndvi.tif"), overwrite=TRUE)
terra::writeRaster(postfire_nbr, paste0(outDir, "/postfire_mean_nbr.tif"), overwrite=TRUE)


# I don't love that I'm using d(mean(NDVI)) instead of mean(dNDVI)
# but I don't have a solution for that right now
dndvi_mean <- prefire_ndvi-postfire_ndvi
dnbr_mean <- prefire_nbr-postfire_nbr

# https://www.un-spider.org/advisory-support/recommended-practices/recommended-practice-burn-severity/in-detail/normalized-burn-ratio

dndvi_mean_plot <- ggplot() +
  geom_spatraster(data=dndvi_mean) +
  ggtitle("Prefire NBR mean") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  scale_color_viridis_c() +
  scale_fill_viridis_c()

dnbr_mean_plot <- ggplot() +
  geom_spatraster(data=dnbr_mean) +
  ggtitle("Prefire NBR mean") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  scale_color_viridis_c() +
  scale_fill_viridis_c()

together <- grid.arrange(dndvi_mean_plot, dnbr_mean_plot, ncol=2)
together


terra::writeRaster(dndvi_mean, paste0(outDir, "HLS_data/diff_mean_ndvi.tif"), overwrite=TRUE)
terra::writeRaster(dnbr_mean, paste0(outDir, "HLS_data/diff_mean_nbr.tif"), overwrite=TRUE)
```




